worker_num: 4
http_port: 18080
dag:
    is_thread_op: false
op:
    uci:
        local_service_conf:
            model_config: uci_housing_model
            devices: "" # "0,1"
            client_type: brpc
